name: my_environment
channels:
  - defaults
dependencies:
  - python=3.11.3
  - pandas=1.5.3
  - numpy=1.24.3
  - lime=0.2.0.1
  - matplotlib=3.7.1
  - requests=2.29.0
  - json5=0.9.6
  - pip=19.3.1
  - pip:
    - pickle
    - uvicorn=0.23.2
    - uvicorn=0.23.2
    - fastapi=0.103.2
    - pydantic=1.10.11
    - streamlit=1.25.0
